blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/thanhtran2408/macgit/discussions
    about: Ask questions or discuss ideas in GitHub Discussions
